[package]
name = "wyvern-mc"
version = "0.0.0"
edition = "2024"

[dependencies]
voxidian-protocol = { workspace = true }
tokio = { workspace = true }
wyvern-actors = { workspace = true }
wyvern-actors-macros = { workspace = true }
futures = { workspace = true }
