[package]
name = "wyvern-mc"
version = "0.0.0"
edition = "2024"

[dependencies]
voxidian-protocol = { workspace = true }
tokio = { workspace = true }
wyvern-macros = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
flume = { workspace = true }
async-net = { workspace = true }
async-io = { workspace = true }
