[package]
name = "wyvern-macros"
version = "0.0.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
rust-format = { workspace = true }
